version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/datas:rw
